//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanStop.TeleTrackClient.ReportingProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xml.teletrack.com/reporting", ConfigurationName="ReportingProxy.ReportingSoap")]
    public interface ReportingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xml.teletrack.com/reporting/ReportData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TransactionResponseSet")]
        LoanStop.TeleTrackClient.ReportingProxy.TransactionResponseSetEntity ReportData(LoanStop.TeleTrackClient.ReportingProxy.TransactionSetEntity TransactionSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xml.teletrack.com/reporting/ReportData", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TransactionResponseSet")]
        System.Threading.Tasks.Task<LoanStop.TeleTrackClient.ReportingProxy.TransactionResponseSetEntity> ReportDataAsync(LoanStop.TeleTrackClient.ReportingProxy.TransactionSetEntity TransactionSet);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/reporting")]
    public partial class TransactionSetEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SoftwareEntity softwareField;
        
        private SubscriberEntity subscriberField;
        
        private TransactionReportEntity[] transactionReportField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string teletrackXMLVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SoftwareEntity Software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
                this.RaisePropertyChanged("Software");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubscriberEntity Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
                this.RaisePropertyChanged("Subscriber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionReport", Order=2)]
        public TransactionReportEntity[] TransactionReport {
            get {
                return this.transactionReportField;
            }
            set {
                this.transactionReportField = value;
                this.RaisePropertyChanged("TransactionReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("TimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TeletrackXMLVersion {
            get {
                return this.teletrackXMLVersionField;
            }
            set {
                this.teletrackXMLVersionField = value;
                this.RaisePropertyChanged("TeletrackXMLVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class SoftwareEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vendorSoftwareIDField;
        
        private string versionNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VendorSoftwareID {
            get {
                return this.vendorSoftwareIDField;
            }
            set {
                this.vendorSoftwareIDField = value;
                this.RaisePropertyChanged("VendorSoftwareID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VersionNumber {
            get {
                return this.versionNumberField;
            }
            set {
                this.versionNumberField = value;
                this.RaisePropertyChanged("VersionNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class TransactionErrorDetailsEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/reporting")]
    public partial class TransactionReportResponseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransactionErrorDetailsEntity[] transactionErrorsField;
        
        private string loanNumberField;
        
        private string transactionCodeField;
        
        private string consumerSSNField;
        
        private System.DateTime loanIssuedDatetimeField;
        
        private bool loanIssuedDatetimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Error", IsNullable=false)]
        public TransactionErrorDetailsEntity[] TransactionErrors {
            get {
                return this.transactionErrorsField;
            }
            set {
                this.transactionErrorsField = value;
                this.RaisePropertyChanged("TransactionErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LoanNumber {
            get {
                return this.loanNumberField;
            }
            set {
                this.loanNumberField = value;
                this.RaisePropertyChanged("LoanNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("TransactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConsumerSSN {
            get {
                return this.consumerSSNField;
            }
            set {
                this.consumerSSNField = value;
                this.RaisePropertyChanged("ConsumerSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LoanIssuedDatetime {
            get {
                return this.loanIssuedDatetimeField;
            }
            set {
                this.loanIssuedDatetimeField = value;
                this.RaisePropertyChanged("LoanIssuedDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoanIssuedDatetimeSpecified {
            get {
                return this.loanIssuedDatetimeFieldSpecified;
            }
            set {
                this.loanIssuedDatetimeFieldSpecified = value;
                this.RaisePropertyChanged("LoanIssuedDatetimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/reporting")]
    public partial class TransactionResponseSetEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransactionReportResponseEntity[] transactionReportResponseField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string subscriberIDField;
        
        private string teletrackXMLVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionReportResponse", Order=0)]
        public TransactionReportResponseEntity[] TransactionReportResponse {
            get {
                return this.transactionReportResponseField;
            }
            set {
                this.transactionReportResponseField = value;
                this.RaisePropertyChanged("TransactionReportResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("TimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
                this.RaisePropertyChanged("SubscriberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TeletrackXMLVersion {
            get {
                return this.teletrackXMLVersionField;
            }
            set {
                this.teletrackXMLVersionField = value;
                this.RaisePropertyChanged("TeletrackXMLVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class BankStatementEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime statementDateField;
        
        private bool statementDateFieldSpecified;
        
        private int numberOfTransactionsField;
        
        private bool numberOfTransactionsFieldSpecified;
        
        private int numberOfNSFsField;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        public BankStatementEntity() {
            this.numberOfNSFsField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime StatementDate {
            get {
                return this.statementDateField;
            }
            set {
                this.statementDateField = value;
                this.RaisePropertyChanged("StatementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatementDateSpecified {
            get {
                return this.statementDateFieldSpecified;
            }
            set {
                this.statementDateFieldSpecified = value;
                this.RaisePropertyChanged("StatementDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfTransactions {
            get {
                return this.numberOfTransactionsField;
            }
            set {
                this.numberOfTransactionsField = value;
                this.RaisePropertyChanged("NumberOfTransactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfTransactionsSpecified {
            get {
                return this.numberOfTransactionsFieldSpecified;
            }
            set {
                this.numberOfTransactionsFieldSpecified = value;
                this.RaisePropertyChanged("NumberOfTransactionsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int NumberOfNSFs {
            get {
                return this.numberOfNSFsField;
            }
            set {
                this.numberOfNSFsField = value;
                this.RaisePropertyChanged("NumberOfNSFs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
                this.RaisePropertyChanged("BalanceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class BankAccountEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BankStatementEntity statementField;
        
        private string bankNameField;
        
        private string bankPhoneNumberField;
        
        private string routingNumberField;
        
        private string accountNumberField;
        
        private AccountTypeType accountTypeField;
        
        private string ownershipField;
        
        private string checkNumberField;
        
        private bool isPresenterOnSiteField;
        
        private bool isPresenterOnSiteFieldSpecified;
        
        private decimal checkAmountField;
        
        private bool checkAmountFieldSpecified;
        
        private string fractionalFormField;
        
        public BankAccountEntity() {
            this.accountTypeField = AccountTypeType.Checking;
            this.ownershipField = "Single";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BankStatementEntity Statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
                this.RaisePropertyChanged("Statement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
                this.RaisePropertyChanged("BankName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BankPhoneNumber {
            get {
                return this.bankPhoneNumberField;
            }
            set {
                this.bankPhoneNumberField = value;
                this.RaisePropertyChanged("BankPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoutingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
                this.RaisePropertyChanged("RoutingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AccountTypeType.Checking)]
        public AccountTypeType AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Single")]
        public string Ownership {
            get {
                return this.ownershipField;
            }
            set {
                this.ownershipField = value;
                this.RaisePropertyChanged("Ownership");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
                this.RaisePropertyChanged("CheckNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPresenterOnSite {
            get {
                return this.isPresenterOnSiteField;
            }
            set {
                this.isPresenterOnSiteField = value;
                this.RaisePropertyChanged("IsPresenterOnSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPresenterOnSiteSpecified {
            get {
                return this.isPresenterOnSiteFieldSpecified;
            }
            set {
                this.isPresenterOnSiteFieldSpecified = value;
                this.RaisePropertyChanged("IsPresenterOnSiteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CheckAmount {
            get {
                return this.checkAmountField;
            }
            set {
                this.checkAmountField = value;
                this.RaisePropertyChanged("CheckAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckAmountSpecified {
            get {
                return this.checkAmountFieldSpecified;
            }
            set {
                this.checkAmountFieldSpecified = value;
                this.RaisePropertyChanged("CheckAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FractionalForm {
            get {
                return this.fractionalFormField;
            }
            set {
                this.fractionalFormField = value;
                this.RaisePropertyChanged("FractionalForm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public enum AccountTypeType {
        
        /// <remarks/>
        Checking,
        
        /// <remarks/>
        Savings,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Money Market")]
        MoneyMarket,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/reporting")]
    public partial class LoanEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoanTypeType loanTypeField;
        
        private System.DateTime openDatetimeField;
        
        private decimal originalBalanceField;
        
        private bool originalBalanceFieldSpecified;
        
        private decimal feesField;
        
        private bool feesFieldSpecified;
        
        private decimal otherFeeAmountField;
        
        private bool otherFeeAmountFieldSpecified;
        
        private string otherFeeTypeField;
        
        private System.DateTime dueDateField;
        
        private decimal currentBalanceField;
        
        private System.DateTime closedDatetimeField;
        
        private bool closedDatetimeFieldSpecified;
        
        private int numberOfPaymentsScheduledField;
        
        private bool numberOfPaymentsScheduledFieldSpecified;
        
        private PaymentFrequencyType paymentFrequencyField;
        
        private bool paymentFrequencyFieldSpecified;
        
        private decimal paymentAmountField;
        
        private bool paymentAmountFieldSpecified;
        
        private AccountStatusType accountStatusField;
        
        private string transactionCodeField;
        
        private string accountNumberField;
        
        private decimal pastDueAmountField;
        
        private bool pastDueAmountFieldSpecified;
        
        private System.DateTime lastPaymentDateField;
        
        private bool lastPaymentDateFieldSpecified;
        
        private decimal actualPaymentAmountField;
        
        private bool actualPaymentAmountFieldSpecified;
        
        private string stateCodeField;
        
        private string reasonCodeField;
        
        private System.DateTime transactionDatetimeField;
        
        private bool transactionDatetimeFieldSpecified;
        
        private LoanEntityPaymentMethod paymentMethodField;
        
        private bool paymentMethodFieldSpecified;
        
        private string checkNumberField;
        
        private string delinquencyStatusField;
        
        private System.DateTime dateOfFirstDelinquencyField;
        
        private bool dateOfFirstDelinquencyFieldSpecified;
        
        private string eCOAIndicatorField;
        
        private string complianceConditionCodeField;
        
        private System.DateTime dateReportedField;
        
        private bool dateReportedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LoanTypeType LoanType {
            get {
                return this.loanTypeField;
            }
            set {
                this.loanTypeField = value;
                this.RaisePropertyChanged("LoanType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime OpenDatetime {
            get {
                return this.openDatetimeField;
            }
            set {
                this.openDatetimeField = value;
                this.RaisePropertyChanged("OpenDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OriginalBalance {
            get {
                return this.originalBalanceField;
            }
            set {
                this.originalBalanceField = value;
                this.RaisePropertyChanged("OriginalBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OriginalBalanceSpecified {
            get {
                return this.originalBalanceFieldSpecified;
            }
            set {
                this.originalBalanceFieldSpecified = value;
                this.RaisePropertyChanged("OriginalBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Fees {
            get {
                return this.feesField;
            }
            set {
                this.feesField = value;
                this.RaisePropertyChanged("Fees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FeesSpecified {
            get {
                return this.feesFieldSpecified;
            }
            set {
                this.feesFieldSpecified = value;
                this.RaisePropertyChanged("FeesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OtherFeeAmount {
            get {
                return this.otherFeeAmountField;
            }
            set {
                this.otherFeeAmountField = value;
                this.RaisePropertyChanged("OtherFeeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherFeeAmountSpecified {
            get {
                return this.otherFeeAmountFieldSpecified;
            }
            set {
                this.otherFeeAmountFieldSpecified = value;
                this.RaisePropertyChanged("OtherFeeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherFeeType {
            get {
                return this.otherFeeTypeField;
            }
            set {
                this.otherFeeTypeField = value;
                this.RaisePropertyChanged("OtherFeeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("DueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CurrentBalance {
            get {
                return this.currentBalanceField;
            }
            set {
                this.currentBalanceField = value;
                this.RaisePropertyChanged("CurrentBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ClosedDatetime {
            get {
                return this.closedDatetimeField;
            }
            set {
                this.closedDatetimeField = value;
                this.RaisePropertyChanged("ClosedDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClosedDatetimeSpecified {
            get {
                return this.closedDatetimeFieldSpecified;
            }
            set {
                this.closedDatetimeFieldSpecified = value;
                this.RaisePropertyChanged("ClosedDatetimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfPaymentsScheduled {
            get {
                return this.numberOfPaymentsScheduledField;
            }
            set {
                this.numberOfPaymentsScheduledField = value;
                this.RaisePropertyChanged("NumberOfPaymentsScheduled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfPaymentsScheduledSpecified {
            get {
                return this.numberOfPaymentsScheduledFieldSpecified;
            }
            set {
                this.numberOfPaymentsScheduledFieldSpecified = value;
                this.RaisePropertyChanged("NumberOfPaymentsScheduledSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PaymentFrequencyType PaymentFrequency {
            get {
                return this.paymentFrequencyField;
            }
            set {
                this.paymentFrequencyField = value;
                this.RaisePropertyChanged("PaymentFrequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentFrequencySpecified {
            get {
                return this.paymentFrequencyFieldSpecified;
            }
            set {
                this.paymentFrequencyFieldSpecified = value;
                this.RaisePropertyChanged("PaymentFrequencySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PaymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
                this.RaisePropertyChanged("PaymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentAmountSpecified {
            get {
                return this.paymentAmountFieldSpecified;
            }
            set {
                this.paymentAmountFieldSpecified = value;
                this.RaisePropertyChanged("PaymentAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccountStatusType AccountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
                this.RaisePropertyChanged("AccountStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("TransactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PastDueAmount {
            get {
                return this.pastDueAmountField;
            }
            set {
                this.pastDueAmountField = value;
                this.RaisePropertyChanged("PastDueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PastDueAmountSpecified {
            get {
                return this.pastDueAmountFieldSpecified;
            }
            set {
                this.pastDueAmountFieldSpecified = value;
                this.RaisePropertyChanged("PastDueAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime LastPaymentDate {
            get {
                return this.lastPaymentDateField;
            }
            set {
                this.lastPaymentDateField = value;
                this.RaisePropertyChanged("LastPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastPaymentDateSpecified {
            get {
                return this.lastPaymentDateFieldSpecified;
            }
            set {
                this.lastPaymentDateFieldSpecified = value;
                this.RaisePropertyChanged("LastPaymentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ActualPaymentAmount {
            get {
                return this.actualPaymentAmountField;
            }
            set {
                this.actualPaymentAmountField = value;
                this.RaisePropertyChanged("ActualPaymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActualPaymentAmountSpecified {
            get {
                return this.actualPaymentAmountFieldSpecified;
            }
            set {
                this.actualPaymentAmountFieldSpecified = value;
                this.RaisePropertyChanged("ActualPaymentAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("ReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TransactionDatetime {
            get {
                return this.transactionDatetimeField;
            }
            set {
                this.transactionDatetimeField = value;
                this.RaisePropertyChanged("TransactionDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDatetimeSpecified {
            get {
                return this.transactionDatetimeFieldSpecified;
            }
            set {
                this.transactionDatetimeFieldSpecified = value;
                this.RaisePropertyChanged("TransactionDatetimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LoanEntityPaymentMethod PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
                this.RaisePropertyChanged("PaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentMethodSpecified {
            get {
                return this.paymentMethodFieldSpecified;
            }
            set {
                this.paymentMethodFieldSpecified = value;
                this.RaisePropertyChanged("PaymentMethodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
                this.RaisePropertyChanged("CheckNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DelinquencyStatus {
            get {
                return this.delinquencyStatusField;
            }
            set {
                this.delinquencyStatusField = value;
                this.RaisePropertyChanged("DelinquencyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateOfFirstDelinquency {
            get {
                return this.dateOfFirstDelinquencyField;
            }
            set {
                this.dateOfFirstDelinquencyField = value;
                this.RaisePropertyChanged("DateOfFirstDelinquency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfFirstDelinquencySpecified {
            get {
                return this.dateOfFirstDelinquencyFieldSpecified;
            }
            set {
                this.dateOfFirstDelinquencyFieldSpecified = value;
                this.RaisePropertyChanged("DateOfFirstDelinquencySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ECOAIndicator {
            get {
                return this.eCOAIndicatorField;
            }
            set {
                this.eCOAIndicatorField = value;
                this.RaisePropertyChanged("ECOAIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComplianceConditionCode {
            get {
                return this.complianceConditionCodeField;
            }
            set {
                this.complianceConditionCodeField = value;
                this.RaisePropertyChanged("ComplianceConditionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DateReported {
            get {
                return this.dateReportedField;
            }
            set {
                this.dateReportedField = value;
                this.RaisePropertyChanged("DateReported");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateReportedSpecified {
            get {
                return this.dateReportedFieldSpecified;
            }
            set {
                this.dateReportedFieldSpecified = value;
                this.RaisePropertyChanged("DateReportedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public enum LoanTypeType {
        
        /// <remarks/>
        AutoEquity,
        
        /// <remarks/>
        Installment,
        
        /// <remarks/>
        SimpleInterest,
        
        /// <remarks/>
        Payday,
        
        /// <remarks/>
        Revolving,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public enum PaymentFrequencyType {
        
        /// <remarks/>
        Daily,
        
        /// <remarks/>
        Weekly,
        
        /// <remarks/>
        Biweekly,
        
        /// <remarks/>
        Semimonthly,
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Quarterly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public enum AccountStatusType {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Paid,
        
        /// <remarks/>
        Chargeoff,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Past Due")]
        PastDue,
        
        /// <remarks/>
        Transferred,
        
        /// <remarks/>
        Void,
        
        /// <remarks/>
        Rescinded,
        
        /// <remarks/>
        NSF,
        
        /// <remarks/>
        Open,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.teletrack.com/reporting")]
    public enum LoanEntityPaymentMethod {
        
        /// <remarks/>
        Check,
        
        /// <remarks/>
        ACH,
        
        /// <remarks/>
        Cash,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class PhoneEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string numberField;
        
        private string extensionField;
        
        private PhoneTypeCodeType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PhoneTypeCodeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public enum PhoneTypeCodeType {
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        Mobile,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        Work,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class ParsedStreetAddressEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string preDirectionField;
        
        private string streetNumberField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string postDirectionField;
        
        private string unitTypeField;
        
        private string unitNumberField;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PreDirection {
            get {
                return this.preDirectionField;
            }
            set {
                this.preDirectionField = value;
                this.RaisePropertyChanged("PreDirection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("StreetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PostDirection {
            get {
                return this.postDirectionField;
            }
            set {
                this.postDirectionField = value;
                this.RaisePropertyChanged("PostDirection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitNumber {
            get {
                return this.unitNumberField;
            }
            set {
                this.unitNumberField = value;
                this.RaisePropertyChanged("UnitNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class PoBoxAddressEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string boxNumberField;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BoxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                this.boxNumberField = value;
                this.RaisePropertyChanged("BoxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class SimpleAddressEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string line1Field;
        
        private string line2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
                this.RaisePropertyChanged("Line1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
                this.RaisePropertyChanged("Line2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class AddressEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SimpleAddressEntity simpleAddressField;
        
        private PoBoxAddressEntity pOBoxAddressField;
        
        private ParsedStreetAddressEntity parsedAddressField;
        
        private string countryField;
        
        public AddressEntity() {
            this.countryField = "United States";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SimpleAddressEntity SimpleAddress {
            get {
                return this.simpleAddressField;
            }
            set {
                this.simpleAddressField = value;
                this.RaisePropertyChanged("SimpleAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PoBoxAddressEntity POBoxAddress {
            get {
                return this.pOBoxAddressField;
            }
            set {
                this.pOBoxAddressField = value;
                this.RaisePropertyChanged("POBoxAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ParsedStreetAddressEntity ParsedAddress {
            get {
                return this.parsedAddressField;
            }
            set {
                this.parsedAddressField = value;
                this.RaisePropertyChanged("ParsedAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("United States")]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class NameEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prefixField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string suffixField;
        
        private string maidenNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
                this.RaisePropertyChanged("Prefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
                this.RaisePropertyChanged("Suffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaidenName {
            get {
                return this.maidenNameField;
            }
            set {
                this.maidenNameField = value;
                this.RaisePropertyChanged("MaidenName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class UINEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string uinField;
        
        public UINEntity() {
            this.typeField = "SSN";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("SSN")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Uin {
            get {
                return this.uinField;
            }
            set {
                this.uinField = value;
                this.RaisePropertyChanged("Uin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/reporting")]
    public partial class ConsumerEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UINEntity uINField;
        
        private NameEntity nameField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private AddressEntity addressField;
        
        private PhoneEntity phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UINEntity UIN {
            get {
                return this.uINField;
            }
            set {
                this.uINField = value;
                this.RaisePropertyChanged("UIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameEntity Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
                this.RaisePropertyChanged("BirthDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AddressEntity Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PhoneEntity Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/reporting")]
    public partial class TransactionReportEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsumerEntity consumerField;
        
        private ConsumerEntity cosignerField;
        
        private LoanEntity loanField;
        
        private BankAccountEntity bankAccountField;
        
        private TransactionReportEntityRecordType recordTypeField;
        
        public TransactionReportEntity() {
            this.recordTypeField = TransactionReportEntityRecordType.New;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConsumerEntity Consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("Consumer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConsumerEntity Cosigner {
            get {
                return this.cosignerField;
            }
            set {
                this.cosignerField = value;
                this.RaisePropertyChanged("Cosigner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LoanEntity Loan {
            get {
                return this.loanField;
            }
            set {
                this.loanField = value;
                this.RaisePropertyChanged("Loan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public BankAccountEntity BankAccount {
            get {
                return this.bankAccountField;
            }
            set {
                this.bankAccountField = value;
                this.RaisePropertyChanged("BankAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TransactionReportEntityRecordType.New)]
        public TransactionReportEntityRecordType RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
                this.RaisePropertyChanged("RecordType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.teletrack.com/reporting")]
    public enum TransactionReportEntityRecordType {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Update,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.teletrack.com/globals")]
    public partial class SubscriberEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberIDField;
        
        private string userNameField;
        
        private string endUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
                this.RaisePropertyChanged("SubscriberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EndUser {
            get {
                return this.endUserField;
            }
            set {
                this.endUserField = value;
                this.RaisePropertyChanged("EndUser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportingSoapChannel : LoanStop.TeleTrackClient.ReportingProxy.ReportingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportingSoapClient : System.ServiceModel.ClientBase<LoanStop.TeleTrackClient.ReportingProxy.ReportingSoap>, LoanStop.TeleTrackClient.ReportingProxy.ReportingSoap {
        
        public ReportingSoapClient() {
        }
        
        public ReportingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LoanStop.TeleTrackClient.ReportingProxy.TransactionResponseSetEntity ReportData(LoanStop.TeleTrackClient.ReportingProxy.TransactionSetEntity TransactionSet) {
            return base.Channel.ReportData(TransactionSet);
        }
        
        public System.Threading.Tasks.Task<LoanStop.TeleTrackClient.ReportingProxy.TransactionResponseSetEntity> ReportDataAsync(LoanStop.TeleTrackClient.ReportingProxy.TransactionSetEntity TransactionSet) {
            return base.Channel.ReportDataAsync(TransactionSet);
        }
    }
}
